name: pymcc
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - cmake
  - cython
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - python-pdal
  - pymcc_lidar
  - pytest
