name: pymcc
channels:
  - anaconda 
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - cmake
  - cython
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - pdal
  - python-pdal
  - fiona
  - pytest
  - pip:
    - git+https://github.com/stgl/pymcc
